[settings]
experimental = true

[tools]
watchexec = "2.5.0"
shellcheck = "0.11.0"

node = "24.14.0"
"npm:corepack" = { version = "0.34.6", postinstall = "corepack enable npm" }
"npm:npm-check-updates" = "19.6.3"
"npm:serve" = "14.2.6"

python = "3.13.12"
uv = "0.9.18"
"pipx:uv-upx" = "0.4.3"
"pipx:fontbakery" = "1.1.0"
"pipx:glyphsLib" = "6.12.7"
"pipx:afdko" = "4.0.3"
"pipx:diffenator2" = { version = "0.4.9", pipx_args = "--preinstall 'setuptools<81' --preinstall 'glyphsLib==6.12.7'", uvx_args = "--with 'setuptools<81' --with 'glyphsLib==6.12.7'" }
"pipx:silfont" = { version = "1.8.0", pipx_args = "--preinstall 'setuptools<81'", uvx_args = "--with 'setuptools<81'" }

rust = "1.93.1"
"cargo:fontspector" = "1.6.0"

[env]
_.python.venv = ".venv"
_.path = ["how2avar2/node_modules/.bin", "infographics/node_modules/.bin"]

UV_PREVIEW_FEATURES = "add-bounds"


[tasks]

[tasks.chmod]
description = "Give mise shell scripts executable permissions"
sources = ["mise/tasks/*.sh"]
run = "chmod -R +x mise/tasks"

[tasks."uv-check-updates.check"]
description = "uv-check-updates check"
run = "uv-upgrade --profile with_pinned --dry-run"

[tasks."uv-check-updates.update"]
description = "uv-check-updates update"
run = "uv-upgrade --profile with_pinned"

[tasks.setup]
run = { tasks = ["**.setup"] }

[tasks."how2avar2.setup"]
sources = ["how2avar2/package.json"]
dir = "how2avar2"
run = "npm install"

[tasks."infographics.setup"]
dir = "infographics"
run = "npm install"
sources = ["infographics/package.json"]

[tasks."fonts.build"]
depends = "fonts.setup"
run = [
  { tasks = [
    "fonts.build.test-font",
    "fonts.build.alternate-glyphs",
    "fonts.build.linear-rotation",
    "fonts.build.quadratic-rotation",
  ] },
]

[tasks."fonts.clean"]
run = ["rm -rf fonts fonts.zip"]

[tasks."fonts.zip"]
description = "Zip font files for release"
sources = ["fonts/**/*"]
depends = "fonts.build"
run = ["rm -rf fonts.zip", "zip -r fonts.zip fonts -x '*.DS_Store'"]
